"""empty message

Revision ID: 1de1b794e701
Revises: 6870f90fb307
Create Date: 2024-10-28 23:58:59.811261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1de1b794e701'
down_revision = '6870f90fb307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.JSON(), nullable=False))
        batch_op.drop_column('when')
        batch_op.drop_column('last_sent')
        batch_op.drop_column('time')

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.alter_column('x_link',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.alter_column('linkdin_link',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.alter_column('insta_link',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.alter_column('github_link',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=225),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('github_link',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('insta_link',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('linkdin_link',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('x_link',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('facebook_link',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('profile_picture',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_sent', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('when', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
