"""empty message

Revision ID: 591bb95a4d9d
Revises: 771acae8a8ab
Create Date: 2024-10-24 07:40:49.379992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591bb95a4d9d'
down_revision = '771acae8a8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sent', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_column('last_sent')

    # ### end Alembic commands ###
