"""empty message

Revision ID: 771acae8a8ab
Revises: 99db99bf28b8
Create Date: 2024-10-23 02:29:37.628488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771acae8a8ab'
down_revision = '99db99bf28b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('file_paths')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_paths', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
