"""Add is_verified column to users

Revision ID: 99db99bf28b8
Revises: 77fa96322cd1
Create Date: 2024-10-22 13:45:41.055719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99db99bf28b8'
down_revision = '77fa96322cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_paths', sa.Text(), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('file_paths')

    # ### end Alembic commands ###
